import './global.css';
import { Inter } from 'next/font/google';
import ParticlesBackground from '@/components/ParticlesBackground';
import Navbar from '@/components/NavBar'; // ✅ You missed this above

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative bg-dark text-light`}>
        <Navbar /> {/* ✅ Add Navbar here */}
        <ParticlesBackground /> {/* ✅ Already present */}
        {children}
      </body>
    </html>
  );
}
